### ISSUE TITLE
[FEAT] 캐릭터 점프 구현, 몬스터가 캐릭터에게 다가옴

### ISSUE THREAD

**Issue by RubiksCube33** [alttabsoft/13-zodiac-signs#14]
## Issue

- 현재 캐릭터 점프 기능이 없음. 점프 기능 구현
- 몬스터가 캐릭터가 있는 쪽으로 오도록 수정

## To-do
- [x] 캐릭터 점프 기능 구현
- [x] 캐릭터 피격 기능 구현
- [x] 캐릭터 기본공격 기능 구현
