### ISSUE TITLE
[FEAT] ATB 및 카메라 이동 구현

### ISSUE THREAD

**Issue by dtd1232** [alttabsoft/13-zodiac-signs#22]
## Issue

- Active Time Battle system 구현하기
- 턴이 바뀌는것에 따른 카메라 이동 구현하기

## ScreenShot
|기능|스크린샷|
|:--:|:--:|
||<img src = "">
||<img src = "">

## To-do
- [ ] 턴제를 ATB로 수정하기
  - [ ] 행동 결정 및 게이지 구현
  - [ ] 행동 게이지 임시 UI 추가
  - [ ] 적 이동 AI
- [ ] 카메라 이동 구현하기
  - [ ] Cinemachine 초기 세팅
  - [ ] ATB에서 플레이어 턴일때 카메라 이동
