### ISSUE TITLE
[FEAT] 캐릭터 그림자, 원거리 몬스터 공격, 점프 시 근거리 피격 안되게 하는 기능 추가

### ISSUE THREAD

**Issue by RubiksCube33** [alttabsoft/13-zodiac-signs#23]
## Issue

캐릭터가 움직일 때 그림자가 따라오도록 추가
원거리 몬스터 및 공격 기능 추가
캐릭터 점프 시 근거리 몬스터에는 피격되지 않도록 하는 기능 추가

카메라 각도 90"의 배수로 변경
(이렇게 안 하니까 캐릭터가 점프 시 사선으로 움직이는 것처럼 보임)

## To-do
- [x] 그림자 추가
- [x] 원거리 몬스터 추가
- [x] 점프 시 근거리 몬스터 피격 무시
- [x] 카메라 각도 조절
